#!/bin/bash
#PBS -l pmem=4gb
#PBS -l walltime=240:00:00
#PBS -j oe
#PBS -A cdm8_f_g_bc_default

set -u
cd /storage/work/s/sug82/NewIPRO_Suite/IPRO/experiments/y/

echo " "
echo " "
echo "Job started on $(hostname -s) at $(date)"
python IPRO.py
echo " "
echo "Job ended at $(date)"
echo " "
